"""initial schema

Revision ID: 775d2d1db8b4
Revises: 
Create Date: 2026-05-04 10:02:41.320332

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775d2d1db8b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_nodes',
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('has_camera', sa.Boolean(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('node_id')
    )
    #op.create_index('idx_graph_nodes_geom', 'graph_nodes', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_graph_nodes_node_id'), 'graph_nodes', ['node_id'], unique=False)
    op.create_table('cameras',
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('fov', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['graph_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('camera_id')
    )
    #op.create_index('idx_cameras_geom', 'cameras', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_cameras_camera_id'), 'cameras', ['camera_id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('edge_id', sa.String(), nullable=False),
    sa.Column('source_node', sa.String(), nullable=False),
    sa.Column('target_node', sa.String(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('lanes', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['source_node'], ['graph_nodes.node_id'], ),
    sa.ForeignKeyConstraint(['target_node'], ['graph_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('edge_id')
    )
    #op.create_index('idx_graph_edges_geom', 'graph_edges', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_graph_edges_edge_id'), 'graph_edges', ['edge_id'], unique=False)
    op.create_table('vision_flows',
    sa.Column('flow_id', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('timestamp_bin', sa.DateTime(), nullable=False),
    sa.Column('period_seconds', sa.Integer(), nullable=False),
    sa.Column('from_edge_id', sa.String(), nullable=True),
    sa.Column('to_edge_id', sa.String(), nullable=True),
    sa.Column('turn_direction', sa.String(), nullable=True),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.Column('avg_speed_mps', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.ForeignKeyConstraint(['from_edge_id'], ['graph_edges.edge_id'], ),
    sa.ForeignKeyConstraint(['to_edge_id'], ['graph_edges.edge_id'], ),
    sa.PrimaryKeyConstraint('flow_id', 'timestamp_bin')
    )
    op.create_index(op.f('ix_vision_flows_flow_id'), 'vision_flows', ['flow_id'], unique=False)
    op.create_index(op.f('ix_vision_flows_timestamp_bin'), 'vision_flows', ['timestamp_bin'], unique=False)
    op.create_table('vision_tracks',
    sa.Column('track_uuid', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=False),
    sa.Column('exit_timestamp', sa.DateTime(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('avg_speed_px', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.PrimaryKeyConstraint('track_uuid', 'entry_timestamp')
    )
    #op.create_index('idx_vision_tracks_geom', 'vision_tracks', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_vision_tracks_entry_timestamp'), 'vision_tracks', ['entry_timestamp'], unique=False)
    op.create_index(op.f('ix_vision_tracks_track_uuid'), 'vision_tracks', ['track_uuid'], unique=False)
    op.create_table('waze_alerts',
    sa.Column('alert_uuid', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('edge_id', sa.String(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('alert_subtype', sa.String(), nullable=True),
    sa.Column('reliability', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['edge_id'], ['graph_edges.edge_id'], ),
    sa.PrimaryKeyConstraint('alert_uuid', 'timestamp')
    )
    #op.create_index('idx_waze_alerts_geom', 'waze_alerts', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_waze_alerts_alert_uuid'), 'waze_alerts', ['alert_uuid'], unique=False)
    op.create_index(op.f('ix_waze_alerts_timestamp'), 'waze_alerts', ['timestamp'], unique=False)
    op.create_table('waze_jams',
    sa.Column('event_uuid', sa.String(), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=False),
    sa.Column('edge_id', sa.String(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('congestion_level', sa.Integer(), nullable=False),
    sa.Column('jam_length_m', sa.Integer(), nullable=False),
    sa.Column('road_type', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['edge_id'], ['graph_edges.edge_id'], ),
    sa.PrimaryKeyConstraint('event_uuid', 'snapshot_timestamp')
    )
    #op.create_index('idx_waze_jams_geom', 'waze_jams', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_waze_jams_event_uuid'), 'waze_jams', ['event_uuid'], unique=False)
    op.create_index(op.f('ix_waze_jams_snapshot_timestamp'), 'waze_jams', ['snapshot_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waze_jams_snapshot_timestamp'), table_name='waze_jams')
    op.drop_index(op.f('ix_waze_jams_event_uuid'), table_name='waze_jams')
    #op.drop_index('idx_waze_jams_geom', table_name='waze_jams', postgresql_using='gist')
    op.drop_table('waze_jams')
    op.drop_index(op.f('ix_waze_alerts_timestamp'), table_name='waze_alerts')
    op.drop_index(op.f('ix_waze_alerts_alert_uuid'), table_name='waze_alerts')
    #op.drop_index('idx_waze_alerts_geom', table_name='waze_alerts', postgresql_using='gist')
    op.drop_table('waze_alerts')
    op.drop_index(op.f('ix_vision_tracks_track_uuid'), table_name='vision_tracks')
    op.drop_index(op.f('ix_vision_tracks_entry_timestamp'), table_name='vision_tracks')
    #op.drop_index('idx_vision_tracks_geom', table_name='vision_tracks', postgresql_using='gist')
    op.drop_table('vision_tracks')
    op.drop_index(op.f('ix_vision_flows_timestamp_bin'), table_name='vision_flows')
    op.drop_index(op.f('ix_vision_flows_flow_id'), table_name='vision_flows')
    op.drop_table('vision_flows')
    op.drop_index(op.f('ix_graph_edges_edge_id'), table_name='graph_edges')
    #op.drop_index('idx_graph_edges_geom', table_name='graph_edges', postgresql_using='gist')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_cameras_camera_id'), table_name='cameras')
    #op.drop_index('idx_cameras_geom', table_name='cameras', postgresql_using='gist')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_graph_nodes_node_id'), table_name='graph_nodes')
    #op.drop_index('idx_graph_nodes_geom', table_name='graph_nodes', postgresql_using='gist')
    op.drop_table('graph_nodes')
    # ### end Alembic commands ###
